### ISSUE TITLE
Vectorized mask values for large images

### ISSUE THREAD

**Issue by HenrikKorsgaardKnowit** [wizart-tech/api#1]
I submitted a large photo to the API (5712 × 4284) with the vectorized_mask set to true. The returned contour coordinates with  largest coordinates in the 2500. I was assuming that the vectorized_mask coordinates mapped to the image size. The result is that the contours / mask does not fit the image. I could not find any documentation on this. 

My solution for now is to resize images before upload, but I wanted to raise the issue if this is a bug on your side. 

Thank you!

**Comment by arturkuchynski** [comment]
@HenrikKorsgaardKnowit  I assume that your Issue relates to our **Vision API SDK** [wizart-sdk-for-python](https://github.com/wizart-tech/wizart-sdk-for-python), or **Vision API** [itself](https://rapidapi.com/wizart-ai-wizart-ai-default/api/vision-api/).

The maximum image size for both width and height is 2560px. We apply downscaling if the incoming image is larger. 

I appreciate you highlighting this lack of documentation. We will update the documentation on the Vision API's RapidAPI page [here](https://rapidapi.com/wizart-ai-wizart-ai-default/api/vision-api/tutorials)

If you have any questions or require further assistance regarding Vision API or Wizart PIM (Automation API) , please do not hesitate to contact [support@wizart.ai](mailto:support@wizart.ai).
